version: '2'

services:
  app:
    build:
      context: .
    environment:
      - RACK_ENV=production5
      - WS_BIND=0.0.0.0
      - WS_PORT=8109
    expose:
      - "8109"
    ports:
      - "80:8109"
    depends_on:
      - db
    networks:
      - app_net
    restart: always

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.10.0/24
        gateway: 192.168.10.1
